blank_issues_enabled: false

contact_links:
  - name: ðŸ“– OpenSC documentation
    url: https://github.com/OpenSC/OpenSC/wiki
    about: Check the documentation and wiki before opening an issue

  - name: ðŸ¤” OpenSC GitHub Discussions
    url: https://github.com/OpenSC/OpenSC/discussions
    about: |
      Ask questions, start discussions, or propose ideas that don't belong in an issue.

  - name: ðŸ’¬ OpenSC mailing lists
    url: https://github.com/OpenSC/OpenSC/wiki/Mailing-lists
    about: For general discussion and usage questions
