blank_issues_enabled: false

contact_links:
  - name: Start a discussion
    url: https://github.com/OpenSC/OpenSC/discussions/new/choose
    about: |
      Ask questions, start discussions, or propose ideas that don't belong in an issue.

  - name: Use the mailing lists
    url: https://github.com/OpenSC/OpenSC/wiki/Mailing-lists
    about: Write us an email or read the archive.
